/*
 * generated by Xtext
 */
package com.ykb.umap.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractProductValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.ykb.umap.dsl.product.ProductPackage.eINSTANCE);
		return result;
	}
}
