/*
* generated by Xtext
*/
package com.ykb.umap.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.ykb.umap.dsl.services.ProductGrammarAccess;

public class ProductParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ProductGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.ykb.umap.dsl.parser.antlr.internal.InternalProductParser createParser(XtextTokenStream stream) {
		return new com.ykb.umap.dsl.parser.antlr.internal.InternalProductParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "UMAPDsl";
	}
	
	public ProductGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ProductGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
