/*
 * generated by Xtext
 */
package com.ykb.umap.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProductUiModule extends com.ykb.umap.dsl.ui.AbstractProductUiModule {
	public ProductUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
