/*
* generated by Xtext
*/
package com.ykb.umap.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ProductUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.ykb.umap.dsl.ui.internal.ProductActivator.getInstance().getInjector("com.ykb.umap.dsl.Product");
	}
	
}
