/*
* generated by Xtext
*/
package com.ykb.umap.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ProductStandaloneSetup extends ProductStandaloneSetupGenerated{

	public static void doSetup() {
		new ProductStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

