/*
 * generated by Xtext
 */
package com.ykb.umap.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProductRuntimeModule extends com.ykb.umap.dsl.AbstractProductRuntimeModule {

}
