/*
 * generated by Xtext
 */
package com.ykb.umap.dsl.ui.contentassist

import com.ykb.umap.dsl.ui.contentassist.AbstractProductProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ProductProposalProvider extends AbstractProductProposalProvider {
}
