/*
 * generated by Xtext
 */
package com.ykb.umap.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.ykb.umap.dsl.ui.internal.ProductActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProductExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ProductActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ProductActivator.getInstance().getInjector(ProductActivator.COM_YKB_UMAP_DSL_PRODUCT);
	}
	
}
